apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:your-org/adama-k8s-core.git
    targetRevision: HEAD
    path: charts/storage
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
    - Replace=true
