apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/atyiadam/adama-k8s-core
    targetRevision: HEAD
    path: charts/test-nginx
    helm:
      valueFiles:
        - values/prod/k8s-01/test-nginx/values.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: test-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
