# replicas: 2 # volume replica count for volumes created from UI
# numberOfReplicas: 2 # volume replica count for volumes created via the StorageClass
# backupTarget: "nfs://10.10.30.2:/volume1/backups/longhorn/k8s-01-prod"
