preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  reclaimPolicy: Retain

service:
  type: ClusterIP

ingress:
  enabled: false

defaultSettings:
  backupTarget: ""
  backupTargetCredentialSecret: ""
