storageClasses:
  synologyNfsCsi:
    enabled: true
    type: nfs-csi
    name: synology-nfs-csi
    isDefault: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    provisioner: nfs.csi.k8s.io
    parameters:
      server: "synology.home.adamatyi.com"
      share: ""
    mountOptions:
      - hard
      - nfsvers=4.1
