csi-driver-nfs:
  controller:
    replicas: 1
  node:
    tolerations: [] 
    
storageClasses:
  media:
    enabled: true
    name: synology-nfs-csi-media
    provisioner: nfs.csi.k8s.io
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    mountOptions:
      - hard
      - nfsvers=4.1
    parameters:
      server: synology.home.adamatyi.com
      share: /volume1/media
      subDir: ""
